{
    "openapi": "3.0.0",
    "info": {
        "title": "Panensia Api Documentation",
        "description": "Panensia api documentation",
        "contact": {
            "email": "panensiaofficial@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://panensia.id/api"
        }
    ],
    "tags": [
        {
            "name": "auth",
            "description": "Authentication user"
        },
        {
            "name": "admin",
            "description": "Api for role admin"
        },
        {
            "name": "user",
            "description": "Api for role user"
        }
    ],
    "paths": {
        "/register": {
            "post": {
                "tags": ["auth"],
                "description": "Register a new user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": [
                                    "email",
                                    "name",
                                    "phone",
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "description": "User email to register"
                                    },
                                    "name": {
                                        "type": "string",
                                        "description": "User name to register",
                                        "minLength": 3,
                                        "maxLength": 55
                                    },
                                    "phone": {
                                        "type": "string",
                                        "description": "User phone number to register",
                                        "minLength": 10,
                                        "maxLength": 13
                                    },
                                    "password": {
                                        "type": "string",
                                        "description": "User password to access acount",
                                        "minLength": 8
                                    }
                                },
                                "example": {
                                    "email": "andika@gmail.com",
                                    "password": "123123123",
                                    "name": "andika",
                                    "phone": "089786567661"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "User register successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "description": "Status request, return true if success and return false if error"
                                        },
                                        "code": {
                                            "type": "integer",
                                            "description": "response code"
                                        },
                                        "message": {
                                            "type": "string",
                                            "description": "response message"
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "access_token": {
                                                    "type": "string",
                                                    "description": "Access token to identify user"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "code": 200,
                                    "message": "User created successfully",
                                    "data": {
                                        "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGJjZDNlNzIwZjZjOWVhMTNhN2I0NGJlNmRlMGU4YjZhYzFjM2UzYjc5Mjg5Y2ExMmY3ZmZiNjY1MjY3NDNhNzI4MWFhYTAyNzEyMThiNTIiLCJpYXQiOjE2OTIwMTIxODIuMzIwMjksIm5iZiI6MTY5MjAxMjE4Mi4zMjAyOTYsImV4cCI6MTY5MjI3MTM4MS45NTY3NzksInN1YiI6IjQiLCJzY29wZXMiOltdfQ.J0gUST1J296_x1sj8K54Ap-MEMqLwhwPsq4UBUhq_geI-v7YbfYuuEQ_a7n8wXy6JrtQJ33yrNeBLDuOval5RX0tEn0Vk852yJm59ZNgJORWiePP_3lnfIpWhUjC2U2PNhbV4GkH8049vv-DkT3r0IVVOFdAlbFxySQp1p_jARCiPMCJz99ml3zuja4acF6FBAwqpNXwdu6l0f3Wo-xz3FYxJkQkr79LrX780t86DUN6p1okzOMolR-NbWiibv-zVM73MsF7ZsJXjEiebdu5KB91saFrqv3G7Svz2MFAWmTKZUhaSLbZDx7V40nRpjL--OgTbm8J_T64DjOpAhN62sadZgW1QET03AP9WNYTCvfNpWaXdPeGBEysLwIeK9U-YN813ZPcUlcQiHyAv5776_hV5r9iv7c_t-p2IMNg6aZ9ZRCEHjLwwOxdP3t2EaYCYPQpulpULj6fwjNCXpKdNOPjJH0VvCXt7u-c2-CaXoYvT__b_5RyHSkwM1fJhEJNFpNicvlch21krI0X4lXYZ5S6uHhKnsOz54K5s2UWeRV43mb1whkCJBbN6lfQS9qD6a9pGtbGzORV-MXjM370aGXuRA54E42pIbY8W26qDjbpGU1J4BYBxTDHfy7-BSrNaEFEiAzfqq36c9qyf9Gk1HzYG-5CBSd6ZIataptsBbo"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "$ref": "#/components/responses/UnprocessableEntitiy"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": ["auth"],
                "description": "Login existing user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["email", "password"],
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string",
                                        "minLength": 8
                                    }
                                }
                            },
                            "example": {
                                "email": "andik@gmail.com",
                                "password": "123123123"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "User Login successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "access_token": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "code": 200,
                                    "message": "User created successfully",
                                    "data": {
                                        "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGJjZDNlNzIwZjZjOWVhMTNhN2I0NGJlNmRlMGU4YjZhYzFjM2UzYjc5Mjg5Y2ExMmY3ZmZiNjY1MjY3NDNhNzI4MWFhYTAyNzEyMThiNTIiLCJpYXQiOjE2OTIwMTIxODIuMzIwMjksIm5iZiI6MTY5MjAxMjE4Mi4zMjAyOTYsImV4cCI6MTY5MjI3MTM4MS45NTY3NzksInN1YiI6IjQiLCJzY29wZXMiOltdfQ.J0gUST1J296_x1sj8K54Ap-MEMqLwhwPsq4UBUhq_geI-v7YbfYuuEQ_a7n8wXy6JrtQJ33yrNeBLDuOval5RX0tEn0Vk852yJm59ZNgJORWiePP_3lnfIpWhUjC2U2PNhbV4GkH8049vv-DkT3r0IVVOFdAlbFxySQp1p_jARCiPMCJz99ml3zuja4acF6FBAwqpNXwdu6l0f3Wo-xz3FYxJkQkr79LrX780t86DUN6p1okzOMolR-NbWiibv-zVM73MsF7ZsJXjEiebdu5KB91saFrqv3G7Svz2MFAWmTKZUhaSLbZDx7V40nRpjL--OgTbm8J_T64DjOpAhN62sadZgW1QET03AP9WNYTCvfNpWaXdPeGBEysLwIeK9U-YN813ZPcUlcQiHyAv5776_hV5r9iv7c_t-p2IMNg6aZ9ZRCEHjLwwOxdP3t2EaYCYPQpulpULj6fwjNCXpKdNOPjJH0VvCXt7u-c2-CaXoYvT__b_5RyHSkwM1fJhEJNFpNicvlch21krI0X4lXYZ5S6uHhKnsOz54K5s2UWeRV43mb1whkCJBbN6lfQS9qD6a9pGtbGzORV-MXjM370aGXuRA54E42pIbY8W26qDjbpGU1J4BYBxTDHfy7-BSrNaEFEiAzfqq36c9qyf9Gk1HzYG-5CBSd6ZIataptsBbo"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "422": {
                        "$ref": "#/components/responses/UnprocessableEntitiy"
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "tags": ["auth"],
                "description": "User profile (All user authenticate using barer)",
                "security": [
                    {
                        "auth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User profile detail",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "integer"
                                                },
                                                "name": {
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "type": "string"
                                                },
                                                "email_verified_at": {
                                                    "type": "string"
                                                },
                                                "phone": {
                                                    "type": "string"
                                                },
                                                "role": {
                                                    "type": "string"
                                                },
                                                "last_login": {
                                                    "type": "string"
                                                },
                                                "created_at": {
                                                    "type": "string"
                                                },
                                                "updated_at": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "code": 200,
                                    "message": "User profile successfully",
                                    "data": {
                                        "id": 4,
                                        "name": "andika",
                                        "email": "andik@gmail.com",
                                        "email_verified_at": null,
                                        "phone": "081123123123",
                                        "role": "user",
                                        "last_login": "2023-08-01 13:57:38",
                                        "created_at": "2023-08-14T11:23:01.000000Z",
                                        "updated_at": "2023-08-14T11:23:01.000000Z"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    }
                }
            },
            "put": {
                "tags": ["auth"],
                "security": [
                    {
                        "auth": []
                    }
                ],
                "description": "Edit profile for user (All user authenticarte using barer)",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["name", "email", "phone"],
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "minLength": 3,
                                        "maxLength": 55
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "phone": {
                                        "type": "string",
                                        "minLength": 10,
                                        "maxLength": 13
                                    }
                                }
                            },
                            "example": {
                                "name": "andika",
                                "email": "andika@gmail.com",
                                "phone": "089767656112"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "User updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "code": 200,
                                    "message": "Profile updated successfully",
                                    "data": true
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "422": {
                        "$ref": "#/components/responses/UnprocessableEntitiy"
                    }
                }
            }
        },
        "/auth/password": {
            "put": {
                "tags": ["auth"],
                "security": [
                    {
                        "auth": []
                    }
                ],
                "description": "Change Password for user that login (All user authenticate using barer)",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["old_password", "new_password"],
                                "properties": {
                                    "old_password": {
                                        "type": "string",
                                        "minLength": 8
                                    },
                                    "new_password": {
                                        "type": "string",
                                        "minLength": 8
                                    }
                                }
                            },
                            "example": {
                                "old_password": "123123123",
                                "new_password": "andikaandika"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "User register successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "code": 200,
                                    "message": "Password changed successfully",
                                    "data": true
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "401": {
                        "$ref": "#/components/responses/Unauthorized"
                    },
                    "422": {
                        "$ref": "#/components/responses/UnprocessableEntitiy"
                    }
                }
            }
        },
        "/forget": {
            "post": {
                "tags": ["auth"],
                "description": "request otp for reset password",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["email"],
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "description": "User email to register"
                                    }
                                },
                                "example": {
                                    "email": "andika@gmail.com"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Password change successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "description": "Status request, return true if success and return false if error"
                                        },
                                        "code": {
                                            "type": "integer",
                                            "description": "response code"
                                        },
                                        "message": {
                                            "type": "string",
                                            "description": "response message"
                                        }
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "code": 200,
                                    "message": "Reset password link sent to your email"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "422": {
                        "$ref": "#/components/responses/UnprocessableEntitiy"
                    },
                    "500": {
                        "$ref": "#/components/responses/InternalServerError"
                    }
                }
            },
            "put": {
                "tags": ["auth"],
                "description": "change password using otp send to the email",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["email", "otp", "new_password"],
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "otp": {
                                        "type": "integer",
                                        "minLength": 6,
                                        "maxLength": 6
                                    },
                                    "new_password": {
                                        "type": "string",
                                        "minLength": 8
                                    }
                                }
                            },
                            "example": {
                                "email": "andika@gmail.com",
                                "otp": 123123,
                                "new_password": "089767656112"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "User register successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "code": 200,
                                    "message": "Password changed successfully"
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/components/responses/BadRequest"
                    },
                    "422": {
                        "$ref": "#/components/responses/UnprocessableEntitiy"
                    }
                }
            }
        },
        "/admin/category": {
            "get": {
                "description": "Get category data (Admin user)",
                "tags": ["admin"],
                "security": [
                    {
                        "auth_admin": []
                    }
                ],
                "parameters": [
                    {
                        "name": "per_page",
                        "in": "query",
                        "required": false,
                        "description": "total data in single page",
                        "schema": {
                            "type": "integer",
                            "nullable": true,
                            "default": 10
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter category by name",
                        "schema": {
                            "type": "string",
                            "nullable": true
                        }
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "required": false,
                        "description": "pagination page",
                        "schema": {
                            "type": "integer",
                            "nullable": true,
                            "default": 1
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        }
    },
    "components": {
        "responses": {
            "BadRequest": {
                "description": "Unmatch credential",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean"
                                },
                                "code": {
                                    "type": "integer"
                                },
                                "message": {
                                    "type": "string"
                                },
                                "errors": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {
                                        "type": "string",
                                        "minLength": 1
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "Unauthorized": {
                "description": "Unautorize",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean"
                                },
                                "code": {
                                    "type": "integer"
                                },
                                "message": {
                                    "type": "string"
                                },
                                "errors": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {
                                        "type": "string",
                                        "minLength": 1
                                    }
                                }
                            }
                        },
                        "example": {
                            "success": false,
                            "code": 401,
                            "message": "Unauthorized",
                            "errors": [
                                "You are not authorized to access this resource"
                            ]
                        }
                    }
                }
            },
            "UnprocessableEntitiy": {
                "description": "User register successfully",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean"
                                },
                                "code": {
                                    "type": "integer"
                                },
                                "message": {
                                    "type": "string"
                                },
                                "errors": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {
                                        "type": "string",
                                        "minLength": 1
                                    }
                                }
                            }
                        },
                        "example": {
                            "success": false,
                            "code": 422,
                            "message": "Unprocessable Entity",
                            "errors": [
                                "The name field is required.",
                                "The email field is required.",
                                "The password field is required.",
                                "The phone field is required."
                            ]
                        }
                    }
                }
            },
            "InternalServerError": {
                "description": "Internal server error",
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean"
                                },
                                "code": {
                                    "type": "integer"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        },
                        "example": {
                            "success": false,
                            "code": 500,
                            "message": "Internal Server Error"
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "auth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "name": "Authorization",
                "in": "header",
                "description": "Authentication for all user role"
            },
            "auth_admin": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "name": "Authorization",
                "in": "header",
                "description": "Authentication for admin role"
            },
            "auth_user": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "name": "Authorization",
                "in": "header",
                "description": "Authentication for user role"
            }
        }
    }
}
